name: CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    name: CI
    steps:
    - name: Setup Go
      uses: actions/setup-go@v2
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Bootstrap
      run: script/bootstrap
    - name: Lint
      run: script/lint
    - name: Test
      run: script/test
    - name: Build
      run: script/build
