name: Releases

on:
  push:
    tags:
      - "v**"

jobs:
  Releases:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go
      uses: actions/setup-go@v2
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set GORELEASER_CURRENT_TAG
      run: echo "GORELEASER_CURRENT_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v1
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}